### ISSUE TITLE
Allow to enable/disable features for Private Construct Hub

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#327]
Define a way for users to pass in a configuration object to the frontend from the Construct Hub construct. This will allow the frontend to include, exclude, or change various content that it owns based on the use case for the deployed instance.

Features that might not be relevant for various instances of construct hub:
* The menu of the main header (or only the FAQ)
* Footer
* Analytics

Additionally, this is required for the implementation of [presentational tags](https://github.com/cdklabs/construct-hub-webapp/issues/340) and [custom links](https://github.com/cdklabs/construct-hub/issues/286).

**Comment by gabewomble** [comment]
@MrArnoldPalmer And I have discussed an approach to this problem that will allow consumers to define build-time configuration of the web app when synthesizing a webapp stack. The general flow is the following:

1. `construct-hub-webapp` will now pack it's own source code, rather than it's build output
2. `construct-hub`'s webapp stack will create a config file for the webapp to use from the stack's parameters
3. When `cdk synth` is called, the `construct-hub-webapp` will be built using config from the created config file.

This config file will be a typescript module that needs to implement an `AppConfig` interface, which will be exported from the `construct-hub-webapp`. This interface defines what is acceptable or required - such as `apiUrl`, `hasAnalytics` and additional config as the feature set is expanded. It will be type-checked both in the stack, as well as when the web app is built to guarantee that the contract between the two is enforced.

**Comment by gabewomble** [comment]
I've marked this as an `effort/epic` because it will require breaking changes in both `construct-hub-webapp` as well as `construct-hub` to implement

**Comment by eladb** [comment]
Not sure I fully understand the design. The above description sounds like we want to bundle the config with the app. Is that correct? I am wondering if its possible to simply deploy an additional `.json` file to the webapp bucket (`BucketDeployment` supports deploying multiple files) and then just `fetch()` it from the client upon initialization.

**Comment by gabewomble** [comment]
Yes, ideally we can bundle the config with the app rather than at run time from a config.json (an idea I originally though of doing). The reason I would prefer to bundle this config with the app (specifically the SSR implementation I've been maintaining) is that it never exposes the config to the client bundle, meaning any future additions to the config which may need to be private can utilize this solution.

Another gotcha with grabbing the config on a client side app is that it wouldn't work for all features. If we want to configure tag functions for example, we can't serve them through a JSON format. Toggling analytics via config also wouldn't work as the analytics script we rely on needs to be the first script on the client

The api I'm proposing from a construct hub consumer's perspective would look like the following:

```ts
new ConstructHub(..., {
  apiUrl: "https://my-private-api.com",
  hasAnalytics: false,
  hasFooter: false,
  tags: [...], // see the Presentational tag proposal
  pages: ["home", "search", "package"],
});
```

With this approach we gain the ability to not only typecheck our config within the construct, but when the webapp builds. This also removes the need to send disabled code (such as pages that aren't included) to the browser

**Comment by MrArnoldPalmer** [comment]
This was solved by https://github.com/cdklabs/construct-hub/pull/418
