### ISSUE TITLE
Sort search results by relevancy (instead of publish date)

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#359]
Search for "assert" --> you get 390 results. @aws-cdk/assertions is not even in the first results page. 

Search for "assertions" --> you get @aws-cdk/assertions only.

**Comment by gabewomble** [comment]
Currently search is very basic b/c it needs to be - it is all handled on the client side (which really is not ideal). The implementation we use now basically stringifies package catalog objects and checks for the presence of the search query in that string.

Realistically if we want to improve our search sorting & filtering, we will first need to lift this work off of the front end to the backend, otherwise we're going to see a large lift in complexity, as well as a potentially significant hit to performance
