### ISSUE TITLE
Implement: Package page - language bar

### ISSUE THREAD

**Issue by iliapolo** [cdklabs/construct-hub-webapp#45]
The Getting Started Area is part of the Package Page Header. It displays information for users that may not have significant information if at all with Constructs and allows them to set their preferred programming language. This should be mostly useful for users who fount the package page through an external search engine (like Google).

## User Actions

* Each construct library/package supports at least one programming language. A user can set their preferred programming language out of the *supported (enabled) programming languages*. The programming languages that are not supported by the displayed package will be *disabled for clicking.*
    * The README, API reference and code samples will be rendered accordingly. 
    * In addition, a *local* *Cookie* will be updated with the programming language that was selected. 
* Make sure to ask for cookie consent before accessing the cookie. If no language is selected, the default is typescript

**Comment by iliapolo** [comment]
> A user can click development quickstart. A new tab will be open with with the relevant CDK quickstart guide. For example, if the construct is of AWS-CDK, it will open the quickstart of AWS-CDK. If it’s a construct of CDK8s, it will open the quickstart guide for CDK8s.

We dont have this information right now in a structured way. jsii does not enforce nor extract any specific key from the `package.json` that may indicate this. Decide what to do.

**Comment by gabewomble** [comment]
Just to clarify a few behaviors in this issue:

- We will be storing a value in localStorage to persist a user's preferred language (not in a cookie)

- The order of priority for a selected language is the following
1. If a valid language is found in a query param in the URL use that first. This will not persist / overwrite a user's preferred language
2. If a valid language is found in localStorage, use that language
3. Otherwise fallback to a default language - which is typescript for now.

We will only update the user preferred language when a user interacts with the language bar.

Something to note is that if a construct only supports a specific language, or the supported languages do not include a user's preferred language, we select the first language the construct supports without overwriting user preferences
