### ISSUE TITLE
Add major version to the package card and package page

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#585]
Some packages have several major versions. Their cards then look as clone of each other unless we add the major version. 

In addition, it's a helpful metadata for the package page.

**Comment by Chriscbr** [comment]
As a hack / alternative, one approach we could try is de-duplicating packages that only differ by major version in the front-end, when we are processing to perform searches. Then on package detail pages, we could include a drop-down to choose between major versions of the package (since this information can be inferred from package.json).
