### ISSUE TITLE
Add tags to the Search Results page

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#684]
Add the tags to the keywords filter on the search results page. 

Once a user pressed a category on the home page, the user will be redirected to the search results page and this tag will be clicked. The relevant search results that have this tag will be displayed. 

Please verify with @gabewomble if the search algorithm already supports searching over tags.

**Comment by gabewomble** [comment]
Can you provide more specific information? I'm not sure there's any work to be done here. @eladb's home page section will just define queries that are not treated as tags / keywords - and the search will work as expect / defined above. Addtionally, the search api does check tags, so if we are adding tags that match these categories, they will show up in search results

I don't agree with mixing keywords and tags because the distinction that keywords are user defined while tags are construct-hub defined is important
