### ISSUE TITLE
Mobile view: the language icons are split to two lines

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#733]
I wonder if we should decrease the size of the language icons for mobile view
![image](https://user-images.githubusercontent.com/11254819/142754582-a2f13bd6-1ea2-46cb-b870-e8321ebd9af0.png)

**Comment by gabewomble** [comment]
I don't think this is something we can effectively solve.

Because these language icons are interactive, it is good practice to give them a large enough size for mobile users to click. It's pretty unavoidable that these will wrap to another line, and bumping the size down is not a guaranteed fix for all mobile phones, nor will it work once we add Go support (meaning another icon will be added).

**Comment by gabewomble** [comment]
Re-verified, looks like the line wrapping doesn't occur on current iPhones which have a width of 375px
