### ISSUE TITLE
Duplicate keywords fix should ignore '-'

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub-webapp#734]
Currently 'cross-region' and 'cross region' are displayed for https://constructs.dev/packages/cdk-remote-stack/v/0.1.215?lang=typescript

though only "Cross Region" is supposed to be displayed.

**Comment by gabewomble** [comment]
I'm not a fan of tackling this on the front-end. Edge cases and scenarios like this are exactly why I was a proponent of using keywords for defining tags, rather than mixing in both and forcing the front end to handle the mapping. Ideally our back-end should be defining a format the front end can display without an additional layer of data-mapping. Even if we fixed a one-off for dashes, this would set a precedent for fixing other "similar" keywords i.e `database` vs `databases`, which won't be scalable.

<img width="337" alt="Screen Shot 2021-11-30 at 10 51 44 AM" src="https://user-images.githubusercontent.com/8749859/144109616-d532d7e9-e798-4368-aee3-5c26004db251.png">
