### ISSUE TITLE
Please support projen constructs

### ISSUE THREAD

**Issue by mbonig** [cdklabs/construct-hub-webapp#906]
I'd love to see projen constructs supported in the service.

**Comment by Chriscbr** [comment]
@mbonig Right now we're holding off on listing projen as another CDK framework because it's still in a very early, experimental state.

But, I'll cue you in on a trick 😉  - currently if your projen library is compiled with jsii and has "cdk" as a keyword on npm (added through your `package.json`), Construct Hub will index it. So, in this way it's possible for projen libraries to be listed, as seen [here](https://d1tmjh4a1bhie.cloudfront.net/packages/projen/v/0.52.66) or [here](https://d1tmjh4a1bhie.cloudfront.net/packages/@pepperize/projen-awscdk-app-ts/v/0.0.60).

**Comment by mrgrain** [comment]
Tracked here: https://github.com/cdklabs/construct-hub/issues/996
